Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-02354e95b39ca8dec
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref MySecurityGroup
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          systemctl start httpd
          systemctl enable httpd
          cd /var/www/html
          <!DOCTYPE html>
<html>
  <head>
    <title>Arquitetura de soluções</title>
  </head>
  <header>
    <nav>
      <ul>
        <li><a href="#sobre">Sobre</a></li>
        <li><a href="#produtos">Produtos</a></li>
      </ul>
    </nav>
  </header>
  <body>
    Somos uma empresa que prove arquitetura de soluções para o seu négocio com o foco diretamente em remodelar o seu ambiente e estruturar para gerar valor a seu cliente final.
  </body> 
  <body>
    <section id="contato">
      <h2>Contato</h2>
      <form action="enviar.php" method="POST">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome">
    
        <label for="email">E-mail:</label>
        <input type="email" id="email" name="email">
    
        <label for="mensagem">Mensagem:</label>
        <textarea id="mensagem" name="mensagem"></textarea>
    
        <button type="submit">Enviar</button>
      </form>
    </body>
    </section>
    <style>
        body {
          font-family: Arial, sans-serif;
        }
      
        header {
          background-color: #333;
          color: #fff;
          padding: 10px;
        }
      
        nav ul {
          list-style: none;
          margin: 0;
          padding: 0;
        }
      
        nav li {
          display: inline-block;
          margin-right: 20px;
        }
      
        nav a {
          color: #fff;
          text-decoration: none;
        }
      
        section {
          margin: 50px 0;
        }
      
        h2 {
          font-size: 24px;
          margin-bottom: 20px;
        }
      
        ul {
          list-style: disc;
          margin: 0;
          padding: 0 0 0 
      
  </body>
</html>
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance
    
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH on Port 22 and Web on Port 80
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80

        
